name: meeting_management
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+11

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.9.2
  flutter_feather_icons: ^2.0.0+1
  flutter_typeahead: ^3.2.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  shamsi_date: ^1.0.0
  universal_html: ^2.0.8
  flutter_svg: ^1.0.3
  file_picker: ^4.3.0
  aligned_dialog: ^0.0.6
  syncfusion_flutter_xlsio: ^19.4.38-beta
  reorderables: ^0.4.2
  country_icons: ^2.0.2
  firebase_messaging: ^11.2.8
  firebase_core: ^1.13.1
  http: ^0.13.4
  flutter_local_notifications: ^9.3.2

  behpardaz_flutter_custom_widget:
    version: ^0.0.40
    git:
      url: http://46.209.222.147:60247/root/behpardaz_flutter_custom_widget.git
  behpardaz_flutter_custom_utility:
    version: ^0.0.25
    git:
      url: http://46.209.222.147:60247/root/behpardaz_flutter_custom_utility.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "res/icon_launcher/logo.png"
  image_path_ios: "res/icon_launcher/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/IRANSans-Medium.ttf
        - asset: assets/fonts/IRANSans-Regular.ttf
        - asset: assets/fonts/IRANSans-UltraLight.ttf
        - asset: assets/fonts/IRANSans-Web.ttf
        - asset: assets/fonts/IRANSans-Web-bold.ttf